services:
  audio-retrieval-app:
    build: .
    container_name: audio-retrieval-app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./configs:/app/configs
      - ./checkpoints:/app/checkpoints
    ports:
      - "8000:8000"
      - "6006:6006"  # Add this for TensorBoard
    command: tail -f /dev/null